name: Build

on:
  push:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            preset: Windows Desktop

          - platform: linux
            preset: Linux/X11

          # - platform: web
          #   preset: Web

          - platform: mac
            preset: macOS

    name: ${{ matrix.preset }} Export
    steps:
      - uses: actions/checkout@v4

      - uses: MechanicalFlower/magic_combo@main
        with:
          command: 'mcx -f .combo.yaml script.add-config-to-github-env'

      - uses: MechanicalFlower/magic_combo@main
        with:
          command: 'mcx -f .combo.yaml script.bump-version'

      - name: Ensure version is equal to tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          [ "${{ env.game_version }}" == "${{ env.BRANCH_NAME }}" ] || exit 2

      - name: Export Marble
        uses: ./.github/actions/export-game
        with:
          name: Marble
          platform: ${{ matrix.platform }}
          preset: ${{ matrix.preset }}
          version: ${{ env.game_version }}
          godot_version: ${{ env.godot_version }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: Marble-${{ matrix.platform }}-v${{ env.game_version }}
          path: build/${{ matrix.platform }}

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        if: ${{ (matrix.platform == 'web') && (env.BRANCH_NAME == 'main') }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        if: ${{ (matrix.platform == 'web') && (env.BRANCH_NAME == 'main') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/web
