name: Build

on:
  push:
    branches: [4.x]
    tags: ['*']
  pull_request:
    branches: [4.x]
  workflow_dispatch:

env:
  tag_name: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            preset: Windows Desktop

          - platform: linux
            preset: Linux/X11

          # - platform: web
          #   preset: Web

          - platform: mac
            preset: macOS

    name: ${{ matrix.preset }} Export
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Versions
        run: |
          pip install magic-combo==0.2.*
          magic_combo script.add-config-to-github-env
          magic_combo script.bump-version --cfg-file export_presets.cfg

      - name: Ensure version is equal to tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          [ "${{ env.game_version }}" == "${{ env.tag_name }}" ] || exit 2

      - name: Export Greeter
        uses: ./.github/actions/export-game
        with:
          name: Greeter
          platform: ${{ matrix.platform }}
          preset: ${{ matrix.preset }}
          version: ${{ env.game_version }}
          godot_version: ${{ env.godot_version }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: Greeter-${{ matrix.platform }}-v${{ env.game_version }}
          path: build/${{ matrix.platform }}

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        if: ${{ matrix.platform == 'web' }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        if: ${{ matrix.platform == 'web' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/web
