name: REUSE Compliance Check

on:
  push:
  workflow_dispatch:

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v2.0.0
