name: Snapcraft Build

on:
  workflow_dispatch:
  # Ensure the build works on main
  push:
    branches: [main]
  # Ensure the build works on each pull request
  pull_request:
  # Build and publish on release
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Load dotenv
        run: just bump-version

      - name: Build snap package
        uses: snapcore/action-build@v1
        with:
          path: public/packaging
        id: snapcraft

      # Push, on each release, to the stable channel
      - uses: snapcore/action-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable
